feat: 가격 제안 모달 구현
price-offer/offer-fe pull request #106
Opened 2023-08-19 09:24 UTC by shinhyojeong

## 🔗 이슈 번호

- closed #101 

## ⛳ 구현 사항
* 가격 제안 모달 구현

## 📚 구현 설명
* 스토리북이 열리지 않아 dev서버에서 테스트했습니다.
* ds
   * Radio에 value prop이 없어 추가해야할 것 같습니다.
   * Button에 disabled에 대한 스타일이 적용되어있지 않아 수정이 필요할 것 같습니다. 
* 필수값에 대한 확인이 필요해 우선운 모든 값을 입력하도록 해놓았습니다 ! (디자이너 확인후 변경사항 반영 예정)

## ⏳ 실행 화면 
### 입력 전
<img width="324" alt="스크린샷 2023-08-19 오후 4 41 34" src="https://github.com/price-offer/offer-fe/assets/70738281/8669bb7e-1d5d-4523-a2eb-9c724d76fb05">

### 입력 후
<img width="445" alt="스크린샷 2023-08-19 오후 6 21 02" src="https://github.com/price-offer/offer-fe/assets/70738281/1e33ad82-f275-4286-a320-44a48e001fa2">

### 택배 거래 선택시
<img width="481" alt="스크린샷 2023-08-19 오후 6 22 08" src="https://github.com/price-offer/offer-fe/assets/70738281/baf84a3d-0025-42ed-b1be-bad6b11457c6">

2023-08-23 09:09 UTC, sonsurim requested changes
스토리북 확인이 필요해서 #110 리뷰가 선행적으로 되어야 할 것 같습니다!
완료 되면 다시 확인 하겠습니다!

2023-09-09 08:43 UTC, shinhyojeong commented
@sonsurim @chojooyoung storybook 디버깅 받와왔숨다 확인 부탁드려용 ☺️~~~

2023-09-27 07:43 UTC, chojooyoung reviewed
코멘트 확인 부탁드립니둥!

2023-09-27 07:43 UTC, chojooyoung commented on src/components/product/PriceOfferModal/index.tsx
> +    !!offerForm.tradeLocation.town
const canOffer =
		offerForm.price &&
		offerForm.tradeMethod &&
		offerForm.tradeLocation.city &&
		offerForm.tradeLocation.country &&
		offerForm.tradeLocation.town; 
		
		이렇게는 안되나요!?

2023-09-27 07:43 UTC, chojooyoung commented on src/components/product/PriceOfferModal/index.tsx
> +    country: 0,
시/군/구 를 담는 필드같은데, county 가 오타나신걸까요...?!

2023-09-28 07:04 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +    country: 0,
region도 괜찮을 것 같아요! 👀

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +    name: 'Incheon'
cspell workspace에 추가해도 좋을 것 같습니다!

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +    country: 0,
혹시 BE 스키마에는 어떻게 되어 있나요???

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +  const handleChangeForm = (
흡 제가 팔로업이 안돼서 그런지 어떤 form이 변경되는지 변수명으로 알 수 있으면 좋을 것 같아요..!

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +    name: 'price' | 'tradeMethod',
이 속성들이 어떤 걸 뜻하는지 따로 타입으로 만들 수 있을까요??

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +    name: keyof OfferForm['tradeLocation'],
아예 타입명으로 선언 하는 것도 좋아 보입니다!

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +            onChange={(e): void => handleChangeForm('price', e.target.value)}
커링으로 하나의 핸들러로 처리하는 형태도 좋을 것 같습니다.
위, 아래 핸들러 함수 확인하지 않고 위에서 로직 파악만 할 수 있어서 좋은 것 같습니다!

- TO-BE

```ts
const handleChangeForm: HandleChangeForm = name => e => {
    const formattedValue = Number(e.target.value.split(',').join(''))

    setOfferForm(prev => ({
      ...prev,
      [name]: formattedValue
    }))
  }
```

```suggestion
            onChange={handleChangeForm('price')}
```

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +                    handleChangeSelectBox('country', item.code)
여기도 위 코멘트와 동일하게 커링으로 하나의 핸들러 형태로 하는 것도 괜찮을 것 같습니다

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +const MOCK_CITY = [
`mocks` 디렉토리가 있어서 mocks에 넣는 것이 좋을 것 같은데
현재 디렉토리 구분이 불분명해서 차주 위클리 때 논의하면 좋을 것 같습니다!
@price-offer/offer-fe

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +  const isTradeDirect = offerForm.tradeMethod !== 8
```suggestion
  const isTradeDirect = offerForm.tradeMethod !== 8
```

@price-offer/offer-fe  8, 4와 같은 매직 리터럴도 논의 후에 수정되면 좋을 것 같습니다

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +          가격이 마음에 든다면, 연락이 올거에요!
@price-offer/offer-fe 
title과 description은 상수화하지 않아도 괜찮을까요??
동일하게 사용되거나 다른 곳에서 상수화 적용하게 되면 함께 반영되면 좋을 것 같습니다!

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/styled.ts
> +`
내부 속성으로 스타일링하시는 이유 여쭤봐도 될까요!?

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/styled.ts
> +  & > div {
저희 SelectBox 테마에 없는건가요?

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/PriceOfferModal.stories.tsx
> +const Template: Story<PriceOfferModalProps> = args => (
스토리북에서 안보이는 것 같아서 확인 부탁드립니다!

2023-09-28 07:45 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +  const [offerForm, setOfferForm] = useState<OfferForm>(initialOfferForm)
BE 스키마랑 맞춰진 형태일까요?? (궁금해서 질문 드립니당!)

2023-09-29 14:18 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +    name: 'Incheon'
요거 mock으로 해놓은 거라 스팩 나온 후에 한번에 작업하는 것이 좋을 것 같은데 어떠신가요 ?

2023-09-29 14:22 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +    country: 0,
헙 오타 맞습니다 ! 수정해놓을게요 🤩!!

@sonsurim 요거 아직 be쪽에서 문서 안나온 부분이라 확인이 필요할 것 같습니다 
(구버전엔 없던 데이터라 제가 임시적으로 추가해 놓았습니다)

2023-09-29 14:26 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +const MOCK_CITY = [
좋아오 ~

2023-09-29 14:29 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +          가격이 마음에 든다면, 연락이 올거에요!
재활용되지 않을 가능성이 높은 문자열이라 처리해놓지 않은 상태입니다 !
(지난번에 페이지단에서 처리한 문자열 상수화가 불필요하다는 의견이 있어 제거한 적이 있습니다!)
요 녀석은 상수화가 필요하다고 생각하신 이유가 궁금합니다 ~

2023-09-29 14:30 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +  const [offerForm, setOfferForm] = useState<OfferForm>(initialOfferForm)
요거 아직 be쪽에서 문서 안나온 부분이라 확인이 필요할 것 같습니다 !

(구버전엔 없던 데이터라 제가 임시적으로 추가해 놓았습니다)

2023-09-29 14:48 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/PriceOfferModal.stories.tsx
> +const Template: Story<PriceOfferModalProps> = args => (
이미지 이슈가 있어서 해당 이슈 처리한 #118 PR rebase 해놓았습니다 !

2023-09-29 14:51 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/styled.ts
> +  & > div {
현재 Selectbox에서 받고있는 prop으론 상위에서 width에 대한 사이즈 컨트롤이 어려운 상태입니다 !
요 스타일 임시적으로 적용해두고 ods-Selectbox에 적용해놓으면 상위에서 width를 컨트롤 하기 좋을 것 같아용 ! 

### 스타일 적용 전
<img width="325" alt="스크린샷 2023-09-29 오후 11 51 20" src="https://github.com/price-offer/offer-fe/assets/70738281/8ac5bcf4-7513-4fd0-a3ff-23f1e193ef0f">

2023-09-29 14:57 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/styled.ts
> +`
중복적인 속성을 적용해야 하는 경우라서 요렇게 처리했습니다 !
생각해보니 요렇게 하는 것 보다 적용하고자 하는 곳에 styled로 감싸서 사용하는게 좋을 듯 하네요 
수정해놓도록 하겠슴다 ~

2023-09-29 15:17 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +    !!offerForm.tradeLocation.town
옷 요렇게 해도 됩니다 ㅎㅎ 수정해놓을게요 ~ ~!

2023-09-29 16:07 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +    !!offerForm.tradeLocation.town
[반영](https://github.com/price-offer/offer-fe/pull/106/commits/983004a8661137d4ecb1cb138f53c818964777cb) 완료!

2023-09-29 16:07 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +    country: 0,
[반영](https://github.com/price-offer/offer-fe/pull/106/commits/983004a8661137d4ecb1cb138f53c818964777cb) 완료!

2023-09-29 16:08 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +            onChange={(e): void => handleChangeForm('price', e.target.value)}
요 함수는 input, form에 대한 changeEvent를 동시에 핸들링하면서 만들어졌는데요 !
input, form 동작에 따라 다르게 실행되야 하는 부분이 있어 두가지 함수를 나누었습니다 ! 
아래 커밋을 확인하시면 됩니다 !

[반영](https://github.com/price-offer/offer-fe/pull/106/commits/983004a8661137d4ecb1cb138f53c818964777cb) 완료!

2023-09-29 16:09 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +                    handleChangeSelectBox('country', item.code)
위와 동일합니다 !

[반영](https://github.com/price-offer/offer-fe/pull/106/commits/983004a8661137d4ecb1cb138f53c818964777cb) 완료!

2023-09-29 16:09 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/styled.ts
> +`
[반영](https://github.com/price-offer/offer-fe/pull/106/commits/983004a8661137d4ecb1cb138f53c818964777cb) 완료!

2023-09-29 16:09 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/PriceOfferModal.stories.tsx
> +const Template: Story<PriceOfferModalProps> = args => (
[반영](https://github.com/price-offer/offer-fe/pull/106/commits/983004a8661137d4ecb1cb138f53c818964777cb) 완료!

2023-10-01 16:35 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +    name: 'Incheon'
그렇다믄 mock 데이터 제거할 때 같이 제거하는 게 좋을 것 같아요!

2023-10-01 16:35 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +          가격이 마음에 든다면, 연락이 올거에요!
안내 문구는 변경될 수도 있을 것 같아서 의견 여쭤보았습니둥 ㅎㅎ

2023-10-01 16:43 UTC, sonsurim commented on src/components/product/PriceOfferModal/index.tsx
> +          onClick={(): void => onClickOffer?.(offerForm)}>
props에 대한 핸들러 함수 전처리 (`?.`)를 해주고 있어서
해당 함수 인라인으로 적지 않고 핸들러로 적는 것이 좋을 것 같은데 어떠신가요?

2023-10-04 12:26 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +          가격이 마음에 든다면, 연락이 올거에요!
상수화 관련해서 정확한 기준을 정하면 좋을 것 같아요 !
다음 회의 때 이야기해봐요 !

2023-10-04 12:27 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/styled.ts
> +  & > div {
[변경](https://github.com/price-offer/offer-fe/pull/106/commits/6469f0116425263c28b10adb34060f794341f9f4) 완료!

2023-10-04 12:27 UTC, shinhyojeong commented on src/components/product/PriceOfferModal/index.tsx
> +          onClick={(): void => onClickOffer?.(offerForm)}>
[변경](https://github.com/price-offer/offer-fe/pull/106/commits/3aa6588ab8c338f5a31f9ea5f196a9bd7cbddb09) 완료 !

2023-10-04 12:33 UTC, sonsurim approved these changes
LGTM 👍👍

고생많으셨습니당!!

2023-10-04 13:24 UTC, merged