feat: 구매자 선택 모달 구현
price-offer/offer-fe pull request #107
Opened 2023-08-20 07:15 UTC by shinhyojeong

## 🔗 이슈 번호

- closed #102 

## ⛳ 구현 사항
* 구매자 선택 모달 구현

## 📚 구현 설명
* 라디오 헤드리스로 개선이 필요해서 수정한 후 다시 작업 진행할 예정입니다.

2023-09-27 07:18 UTC, chojooyoung submitted a review, later dismissed
고생하셨숩니다~! 코멘트만 확인해주세요!

2023-09-27 07:18 UTC, chojooyoung commented on src/components/mypage/SelectBuyerModal/styled.ts
> +  min-width: fit-content;
min-width: fit-content; 
위 공백 제거 해도 될 것 같습니다!

2023-09-27 07:18 UTC, chojooyoung commented on src/components/mypage/SelectBuyerModal/index.tsx
> +            nickname,
보통 nickname은 nickName 으로 하는 관례가 보편화되어 있지 않나요?.?!

2023-09-28 07:56 UTC, sonsurim requested changes

2023-09-28 07:56 UTC, sonsurim commented on src/components/mypage/SelectBuyerModal/index.tsx
> +            nickname,
이참에 정하시쥬!!

2023-09-28 07:56 UTC, sonsurim commented on src/components/mypage/SelectBuyerModal/index.tsx
> +  handleClickReviewButton,
@price-offer/offer-fe 
컴포넌트 내부에서 핸들러 함수를 정의할 때, `handle` prefix를 붙이고
props로 전달할 때는 `on` prefix로 컨벤션 정의하는 건 어떠신가요?

```suggestion
  onClickReviewButton,
```

2023-09-28 07:56 UTC, sonsurim commented on src/components/mypage/SelectBuyerModal/index.tsx
> +  const [selectedBuyerId, setSelectedBuyerId] = useState<number>(0)
```suggestion
  const [selectedBuyerId, setSelectedBuyerId] = useState(0)
```
명시적으로 추론되는 값은 타입을 적지 않아도 괜찮을 것 같은데 어떠신가요?

2023-09-28 07:56 UTC, sonsurim commented on src/components/mypage/SelectBuyerModal/styled.ts
> +
공백은 stylelint 때문에 생긴걸까요???

2023-09-28 07:56 UTC, sonsurim commented on src/components/mypage/SelectBuyerModal/styled.ts
> +  }
간단한 UI 지만 속성으로 스타일링 하게되면 추후 디버깅이 어려워질 것 같아서 개인적으로 styled 컴포넌트로 만들어주는 게 좋을 것 같은데 어떠신가요?

2023-09-29 14:09 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/styled.ts
> +  min-width: fit-content;
요 여백은 stylelint 규칙에 따라서 적용되고 있어요 !!

2023-09-29 14:10 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/index.tsx
> +  handleClickReviewButton,
좋심더 cc @chojooyoung

2023-09-29 14:10 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/styled.ts
> +
네 ! 맞습니다 !

2023-09-29 14:15 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/index.tsx
> +            nickname,
nickname이 하나의 명사여서 요대로 사용하는게 맞는 것 같숨다 ! 또 백에서도 nickname으로 내려오고 있어용 !

2023-09-29 14:16 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/index.tsx
> +  handleClickReviewButton,
[적용](https://github.com/price-offer/offer-fe/pull/107/commits/dbe833d84018b54c74b18926d7f84e1c03b5ba2d) 완룡

2023-09-29 14:16 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/index.tsx
> +  const [selectedBuyerId, setSelectedBuyerId] = useState<number>(0)
[적용](https://github.com/price-offer/offer-fe/pull/107/commits/dbe833d84018b54c74b18926d7f84e1c03b5ba2d) 완룡

2023-09-29 14:16 UTC, shinhyojeong commented on src/components/mypage/SelectBuyerModal/styled.ts
> +  }
[적용](https://github.com/price-offer/offer-fe/pull/107/commits/dbe833d84018b54c74b18926d7f84e1c03b5ba2d) 완룡

2023-10-01 16:47 UTC, sonsurim approved these changes
LGTM 👍

2023-10-02 13:25 UTC, merged

2023-10-02 13:26 UTC, shinhyojeong commented
@sonsurim  @chojooyoung 
요거 ods의 [refactor: Radio 컴포넌트 확장성있게 변경](https://github.com/price-offer/offer-design-system/pull/185)에 의존성 있는데 머지 해버렸네요 ㅠ 
ods version 업하고 추가적으로 수정 작업 하겠습니다 !