Feat: 가격제안, 거래후기, 거래후기 확인 모달 작업
price-offer/offer-fe pull request #108
Opened 2023-08-20 10:10 UTC by chojooyoung

## 🔗 이슈 번호

- closed #105 
가격제안, 거래후기, 거래후기 확인 모달 작업입니다.

## ⛳ 구현 사항

## 📚 구현 설명

2023-08-23 09:11 UTC, sonsurim requested changes
스토리북 확인이 필요해서 #110 리뷰가 선행적으로 되어야 할 것 같습니다!
완료 되면 다시 확인 하겠습니다!

2023-09-09 05:50 UTC, shinhyojeong commented on src/components/mypage/ReviewConfirmModal/types.ts
> +}
offer-ui에 있는 Modal의 prop과 겹치는 타입들은 ModalProps 타입을  extends 해오는 것이 좋을 것 같습니다 !

2023-09-09 08:05 UTC, shinhyojeong reviewed
주영님 넘 수고하셨어요 ! 컴포넌트를 조금 더 확장성있게 가져가고, 코드의 중복도 줄이는 방식으로 수정해주시면 더 좋을 것 같습니다 ☺️!

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +    string | 'smile' | 'meh' | 'sad'
string이 `smile`, `meh`, `sad` 타입을 포함하기 때문에 string이 추가되면 다른 타입들을 추가할 필요가 없을 것 같아요 `smile`, `meh`, `sad` 외에도 사용될 여지가 있을까요 ?! 단순히 기본값을 넣기 위한거면 null 타입을 추가하는 것이 더 좋은 방법일 것 같습니다 ! 추가로 요 타입은 offer-ui 아이콘타입에서 사용하는 타입을 Pick해서 가져오는 것은 어떠신가요 ?

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewConfirmModal/index.tsx
> +  }
저는 해당 UI의 모달을 AlertModal 정도로 정의해서 common 폴더의 컴포넌트로 빼는 것을 생각했어요 ! AlertModal 모달은 버튼 선택지를 하나만 두어 **정보의 확인** 목적으로 사용하는 모달로 사용하면 좋겠다고 생각했습니다 !
현재 만들어진 ReviewConfirmModal은 리뷰 확인 목적으로만 사용할 수 있을 것 같은데, 정보를 알려줄 message와 확인 클릭시 동작할 함수를 prop으로 받아 확장성있게 수정하는 것은 어떠신가요 ?

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewConfirmModal/styled.ts
> +  ModalContainer,
ModalContainer, Container가 두가지 존재해서 어떤 차이가 있는지 와닿지 않는 것 같은데 ModalContainer -> Modal로 수정하는 것은 어떠신가용?

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  argTypes: {},
사용 안하는 속성은 제거되는 것이 좋을 것 같아요 !

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  title: 'Components/MyPage/ProfileBox'
제가 [스토리북 디렉토리 정리하는 PR](https://github.com/price-offer/offer-fe/pull/117) 올려두었는데 정리된 것에 맞춰 Components/를 빼야될 것 같습니다 !

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +          <Styled.ReviewIcon
중복되는 것을 더 나은 방식으로 처리할 수 있을 것 같습니다🤔!

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
inputLength, reviewText, reviewEvaluate를 따로 상태로 관리할 필요가 있을까요 ? review와 관련된 form을 하나의 state로 관리해도 좋을 것 같고, inputLength는 
 reveiwForm.text 같은 값으로 판단되어도 될 것 같아요 !

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +            }></Styled.GoodIcon>
횬재 저희 디자인 시스템에 toggleIcon이 있는데 이것을 사용하거나, 사용하지 않는게 낫다고 판단되면 해당 컴포넌트를 제거하는 방식으로 수정되어야 할 것 같습니다 @sonsurim @chojooyoung

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/styled.ts
> +  ${({ theme }): string => theme.fonts.body01M};
중복이라 스타일을 한곳에서 관리해서 적용하면 좋을 것 같아요 !

2023-09-09 08:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +  }
send할 때 실행할 함수를 prop으로 받아야할 것 같아요 !

2023-09-09 10:27 UTC, shinhyojeong commented on src/components/mypage/ReviewConfirmModal/index.tsx
> +  }
> 정보의 확인 목적으로 사용하는 모달
만약 위 목적으로 모달을 변경한다면 하단의 경우에도 대응해 사용하면 좋을 것 같습니다 !

<img width="214" alt="스크린샷 2023-09-09 오후 7 26 47" src="https://github.com/price-offer/offer-fe/assets/70738281/27c51de4-653c-4cbb-8ea5-7727e2122f43">

2023-09-09 11:47 UTC, shinhyojeong commented
주영님 ! 하단의 읽기 모드에 대한 모달도 대응 되어 있는 걸까용 ?
<img width="458" alt="스크린샷 2023-09-09 오후 8 46 58" src="https://github.com/price-offer/offer-fe/assets/70738281/4a66eebe-0d61-4871-8fd4-8f1e4f3372c8">

2023-09-09 15:42 UTC, chojooyoung commented on src/components/mypage/ReviewConfirmModal/styled.ts
> +  ModalContainer,
넵 더 명확하게 ReviewModal 로 하겠씁니당~

2023-09-09 16:06 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +            }></Styled.GoodIcon>
이걸 사용했을때 해당 모달에서 쓰이는 svg가 디자인과 달라 커스텀하였습니다

2023-09-09 16:41 UTC, chojooyoung commented
> 주영님 ! 하단의 읽기 모드에 대한 모달도 대응 되어 있는 걸까용 ? <img alt="스크린샷 2023-09-09 오후 8 46 58" width="458" src="https://user-images.githubusercontent.com/70738281/266778473-4a66eebe-0d61-4871-8fd4-8f1e4f3372c8.png">

오 아니요 해당 모달도 할당 되어있었나요...? ㅎㅎ; 
맞다면 같이해서 올리겠습니다

2023-09-10 06:42 UTC, shinhyojeong commented
@chojooyoung 
> 오 아니요 해당 모달도 할당 되어있었나요...? ㅎㅎ;
맞다면 같이해서 올리겠습니다

구조가 리뷰 작성과 유사해서 같은 컴포넌트로 관리돼도 괜찮을 것 같슴다 ! 😃

2023-09-10 06:46 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +            }></Styled.GoodIcon>
헙 toggleButton이 Icon을 가지고 만들어진 컴포넌트라 두가지 동일한 아이콘 모양이 나올 것으로 기대되는데 혹시 어떻게 다를까용 !?

2023-09-10 08:26 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +            }></Styled.GoodIcon>
일단 good 모양의 icon자체가 다른 평가상태의 아이콘들이랑 굵기가 달라서 임의적으로 만들었구요,
toggle 형식이라 isToggle props가 제대로 동작안하고 다른걸 선택해도 계속 toggle 이 유지되는 현상이 있어 그냥 구현했습니다 ㅠ
<img width="350" alt="image" src="https://github.com/price-offer/offer-fe/assets/66211721/55f44f24-bec6-4f8d-99a6-8697237784f8">

<img width="365" alt="image" src="https://github.com/price-offer/offer-fe/assets/66211721/26169436-ec3c-467f-a5c3-88d4b40c937f">

2023-09-11 06:54 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +            }></Styled.GoodIcon>
ㅎㅎ그렇군요 ! 저는 toggleIcon을 굳이 컴포넌트화해서 사용하지 않아도 좋을 것 같아요 ! 간단하게 Icon을 button으로 감싸서 구현할 수 있는 부분이라 ds에서 관리되면 오히려 유지보수가 어려워질 것 같습니다 ! 주영님이 구현하신 대로 가규 ds에 toggle을 제거하는 것이 좋을 것 같아웅 🤩

2023-09-28 07:51 UTC, chojooyoung commented on src/components/mypage/ReviewConfirmModal/types.ts
> +}
완료!

2023-09-28 07:51 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +    string | 'smile' | 'meh' | 'sad'
완료!

2023-09-28 07:51 UTC, chojooyoung commented on src/components/mypage/ReviewConfirmModal/index.tsx
> +  }
완료!

2023-09-28 07:51 UTC, chojooyoung commented on src/components/mypage/ReviewConfirmModal/styled.ts
> +  ModalContainer,
완료!

2023-09-28 07:51 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  argTypes: {},
완료!

2023-09-28 07:51 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  title: 'Components/MyPage/ProfileBox'
완료!

2023-09-28 07:52 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +          <Styled.ReviewIcon
완료!

2023-09-28 07:52 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
완료!

2023-09-28 07:52 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +            }></Styled.GoodIcon>
완료!

2023-09-28 07:52 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +  }
완료!

2023-09-28 07:52 UTC, chojooyoung commented
> @chojooyoung
> 
> > 오 아니요 해당 모달도 할당 되어있었나요...? ㅎㅎ;
> > 맞다면 같이해서 올리겠습니다
> 
> 구조가 리뷰 작성과 유사해서 같은 컴포넌트로 관리돼도 괜찮을 것 같슴다 ! 😃

완료!

2023-09-28 08:22 UTC, sonsurim requested changes

2023-09-28 08:22 UTC, sonsurim commented on src/components/common/AlertModal/index.tsx
> +  isCheckShape = false,
```suggestion
  hasCheckIcon = false,
```
체크 아이콘이 보여지는 형태여서 has로 표현되면 좋을 것 같은데 위 변수명은 어떠신가요?

2023-09-28 08:22 UTC, sonsurim commented on src/components/common/AlertModal/index.tsx
> +  onClick
```suggestion
  onConfirm
```
변수명에 혼란이 있을 것 같아 onConfirm도 괜찮을 것 같습니다!

2023-09-28 08:22 UTC, sonsurim commented on src/components/common/AlertModal/index.tsx
> +  }
별도의 처리를 해주지 않는다면 인라인으로 넣어도 괜찮을 것 같아요!

2023-09-28 08:22 UTC, sonsurim commented on src/components/common/AlertModal/index.tsx
> +      <Styled.ReviewConfirmButton onClick={handleClickConfirmModal}>
```suggestion
      <Styled.ReviewConfirmButton onClick={onConfirm}>
```

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  const [isOpen, setIsOpen] = useState<boolean>(false)
open, close 다루는 state가 많이 사용될 것 같은데 커스텀 훅으로 만들어도 괜찮을 것 같습니다!

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +const evaluateData: EvaluateData = [
`evaluate`가 서비스에서 생소한 단어인 것 같아서 `score` 정도로 표현해도 괜찮을 것 같은데 어떠신가요?
+ BE에서는 어떻게 사용되는지 여쭤봐도 될까요??

```suggestion
const MOCK_SCORE: Score = [
```

상수 mock은 대문자로 표현되면 좋을 것 같습니다

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +  onClick,
```suggestion
  onConfirm,
```
여기두 onConfirm이 명확할 것 같아요!

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +  readModeReviewContent = '리뷰'
```suggestion
  score = 'smile',
  contents = '리뷰'
```
이미 컨텍스트가 포함되어 있어서 props명에서 readMode를 생략하고 타입으로 isReadMode가 true일 때만 해당 props를 받을 수 있는 형태가 좋을 것 같습니다!

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
```suggestion
  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(isReadMode)
```
`isReadMode`를 기본값으로 주면 126라인에서 크로스 체크 안해도 괜찮을 것 같아요!

```ts
 <Styled.ReviewSendButton
        disabled={isReadMode ? false : !isClickReviewIcon}
        styleType={
          isClickReviewIcon ? 'solidPrimary' : 'solidDisabled'
        }
        onClick={handleClickSendReview}>
        {isReadMode ? '확인' : '후기 보내기'}
      </Styled.ReviewSendButton>
```

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +    inputLength: 0,
```suggestion
```

reviewText를 관리하고 있는데 inputLength가 있어 input과 review가 다른 데이터를 의미하는 것 같습니다.

`reviewText.length`를 활용하는 형태가 더 좋을 것 같습니다!

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +  }
여기도 전,후 처리 없는 경우 인라인으로 적어주어도 무방할 것 같습니다!

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/styled.ts
전체적으로 stylelint 설정이 반영 안된 것 같습니다!

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/styled.ts
> +
```suggestion
cursor: pointer;

```
커서가 포인터로 적용되면 좋을 것 같아요

2023-09-28 08:22 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
ReadMode에 대한 분기처리가 이루어지다 보니 view 영역의 코드 파악이 조금 복잡해진 것 같습니다! 혹시 분리하는 건 어떠신가요??

2023-09-28 09:13 UTC, shinhyojeong reviewed
주영님 수고하셨어요 ! 반영사항 리뷰 남깁니다 ☺️

2023-09-28 09:13 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/types.ts
> +  'isOpen' | 'onClose' | 'children'
리뷰 모달에서 children을 넘겨서 사용하지 않을 것 같아서 Pick하지 않아도 될 것 같습니다 !

2023-09-28 09:13 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +                    isGood={evaluate.state === 'smile'}
요거 아이콘이 굿일 때만 다르게 보여서 처리하신 것으로 파악되는데,
아이콘 파일측에서 해당 이슈를 해결해주면 오 처리가 불필요해질 것 같습니다 🤩!!

2023-09-28 09:13 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/types.ts
> +  nickName: string
nickname자체가 명사라 카멜케이스로 사용하지 않는 것이 맞는 것 같아용 !
be쪽에서 nickname으로 내려오고 있어서 통일하는 것이 좋을 것 같습니다 !

2023-09-28 09:13 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +        </Styled.ReadModeReviewContentArea>
단순 호기심인데 Area, Container를 사용하는 기준이 있을까용 ? 
두가지 모두 사용되고 있는데 줭님은 어떤 기준으로 사용하시는지 궁금합니다 !

2023-09-29 07:14 UTC, chojooyoung commented on src/components/common/AlertModal/index.tsx
> +  onClick
오 그렇네요! 
더 확실하게 onClickComfirmButton으로 하겠습니다!

2023-09-29 08:03 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  const [isOpen, setIsOpen] = useState<boolean>(false)
오 좋습니다!!
해당 Pr에 적용해서 한번 리뷰 또 따로 받아도 괜찮을까요?.?

2023-09-29 08:05 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +const evaluateData: EvaluateData = [
넵 score가 더 일반적이고 좋은 것 같습니다 ㅎㅎ
<img width="890" alt="image" src="https://github.com/price-offer/offer-fe/assets/66211721/1ee089df-7836-4689-8151-185ca7d7816c">
백엔드도 스코어네요!!

2023-09-29 14:30 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
음 저도 그렇게 생각해요...! 
효정님 첫 리뷰때 구성이 비슷해서 같이 올라가면 좋을 것 같다는 의견에 동의해서 했는데, 막상 짜고보니 의견에 동의합니당

분리라면 혹시 컴포넌트 안에서 분리를 말씀하시는 걸까요??
제 생각엔 readMode의 모달은 본래 ReviewModal이랑(리뷰보내기) 성격이 다른거라 아예 다른 모달(ReadReviewModal?) 컴포넌트로 분리하는것이 더 나아 보이는데요!
일단 컴포넌트 내에서 분리시켜보았는데 보시고 의견주시면 감사하겠습니당
[컴포넌트 내 분리](https://github.com/price-offer/offer-fe/pull/108/files#diff-4b8ae2495983bb2ac6378048f00a9113a977027de98963d259a27f5437cb9424)
@shinhyojeong @sonsurim

2023-09-29 14:38 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        </Styled.ReadModeReviewContentArea>
아 ReadMode가 아닐때 저 부분이  <TextArea>  태그 라서 Area를 붙혀 사용했는데, 
의도와 달리 해석하신걸로 보아 제가 잘못짯네요 말씀주신 Container와 의미가 겹치기도 하구요.
Content로 변경이 더 나아보입니다! 그렇게 변경할게요!

2023-09-30 06:36 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  const [isOpen, setIsOpen] = useState<boolean>(false)
[useModals Hook](https://github.com/price-offer/offer-fe/pull/108/files#diff-f190e52fa9f765e1a6a06c0c06f5bba534eb50390f4d56c264bd91202c674e62) 
같이 봐주세용! @shinhyojeong @sonsurim

2023-10-01 11:14 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +  }
open, close 보다 명확하게 openModal, closeModal 같은 이름이면 좋을 것 같아요 !

2023-10-01 11:14 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +  )
요렇게 여러개의 모달을 관리하고자 한다면 전역적으로 관리되는 것이 좋을 것 같은데 어떠신가융 ?

2023-10-01 11:14 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +        </Styled.ReadModeReviewContentArea>
오홍 Textarea를 생각하신 거였군요 !

> 의도와 달리 해석하신걸로 보아 제가 잘못짯네요 말씀주신 Container와 의미가 겹치기도 하구요.

저도 의미를 확인하고 나니 더 명확하게 하기 위해 수정하신 것이 더 좋은 것 같습니다 👍!!

2023-10-01 11:16 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
저는 공통된 부분이 많아서 read와 write를 나누어 처리한다면
아이콘 셀렉하는 부분만 빼서 처리하는 것이 더 좋을 것 같다는 생각이 듭니다 !

2023-10-01 11:19 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +const useModals = (modalIds: string[]): UseModalReturnType => {
현재 모달을 여러개 관리하지 않아도 되는 상황에서 
모달의 이름을 정해서 사용해야하는 불편함을 감수하면서라도 
요렇게 여러개를 관리하도록 짜는 것이 나은지 고민이 되네요 🤔

저는 현재 상황에서 사용하는데 더 편리하게 하는 것이 나을 것 같다는 의견입니다 !

2023-10-01 16:52 UTC, sonsurim commented on src/hooks/useModals.ts
> +  }
useModal에서 Modal이라는 Context를 포함하고 있어서 Modal을 안붙여줘도 될 것 같아요!

2023-10-01 16:55 UTC, sonsurim commented on src/hooks/useModals.ts
> +const useModals = (modalIds: string[]): UseModalReturnType => {
앗 제가 레퍼런스를 남겨두지 않아서 의미가 잘못 전달된 것 같습니다..! 죄송합니둥..
[useDisclosure](https://chakra-ui.com/docs/hooks/use-disclosure) 정도의 커스텀 훅으로 생각했는데 혹시 모달 사용하는 쪽에서 재사용할 수 있게 요런 느낌의 훅을 만드는 건 어떠신가요??

2023-10-01 17:00 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
@chojooyoung 님, 지금처럼 컴포넌트로 나뉘어진 형태가 좋은 것 같습니당!
코멘트 남겨주신 부분 확인하고 아래 의견 추가로 생각해보았는데 혹시 어떠신지 여쭤봅니다!
1. ReviewModal/index가 아닌 각각 파일로 분리 (`WriteReviewModal/index.tsx`)
2. 1번 혹은 사용할 때, 아래처럼 사용할 수 있게 ReviewModal index 내부 컴포넌트로 관리
`<ReviewModal.Read/>` 혹은 `<ReviewModal.Write/>`
- 인터페이스가 다른데 하나의 컴포넌트이다 보니 2로 했을 때, 의미 전달이 더 좋을 것 같기도 해서 1, 2 둘 다 여쭤봅니당!

2023-10-02 15:55 UTC, chojooyoung commented on src/components/mypage/ReviewModal/styled.ts
완료! 
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/70e9b2fc0526dc847b91765e7a144bc553cdde4b#diff-092c68daeb532a31194e00eb9e22ee754578f8d45d31aa908f8fd4e817f97dfb)

2023-10-02 16:03 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
해당 요구사항 선반영 하였으나, 
Read/Write 컴포넌트 로직 분리가 결정되면 resolve 하겠습니다!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/2f6a4f180e5cc19c7c09ed82b4805a718940c178#diff-4b8ae2495983bb2ac6378048f00a9113a977027de98963d259a27f5437cb9424)

2023-10-02 16:05 UTC, chojooyoung commented on src/components/mypage/ReviewModal/types.ts
> +  nickName: string
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/f6180b858018de6337c80530a23343d9ca304ad3)

2023-10-02 16:06 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReviewModal.stories.tsx
> +  argTypes: {},
[완료](https://github.com/price-offer/offer-fe/pull/108/commits/f6180b858018de6337c80530a23343d9ca304ad3)

2023-10-02 16:08 UTC, chojooyoung commented on src/components/common/AlertModal/index.tsx
> +  isCheckShape = false,
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/2f6a4f180e5cc19c7c09ed82b4805a718940c178#diff-08768223cb51d41ee8726f9e11b78640fecff8209b3c03c0986f90775f3fb7f8)

2023-10-02 16:08 UTC, chojooyoung commented on src/components/common/AlertModal/index.tsx
> +  onClick
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/2f6a4f180e5cc19c7c09ed82b4805a718940c178#diff-08768223cb51d41ee8726f9e11b78640fecff8209b3c03c0986f90775f3fb7f8)

2023-10-02 16:09 UTC, chojooyoung commented on src/components/common/AlertModal/index.tsx
> +  }
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/2f6a4f180e5cc19c7c09ed82b4805a718940c178#diff-08768223cb51d41ee8726f9e11b78640fecff8209b3c03c0986f90775f3fb7f8)

2023-10-02 16:09 UTC, chojooyoung commented on src/components/common/AlertModal/index.tsx
> +      <Styled.ReviewConfirmButton onClick={handleClickConfirmModal}>
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/2f6a4f180e5cc19c7c09ed82b4805a718940c178#diff-08768223cb51d41ee8726f9e11b78640fecff8209b3c03c0986f90775f3fb7f8)

2023-10-02 16:12 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
분리를 하게 된다면 수림님 의견데로 2번이 의미전달이 더 좋아보입니다!! 2번안으로 반영후 요청드리겠습니다!!!

2023-10-02 16:12 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
@shinhyojeong 님, 저도 짜려고 보니 하나의 컴포넌트안에 로직처리가 간단하지 않더라구요 ㅠㅠ 분리를 하는 쪽으로 생각하고 있는데, 
설득이 되실까요...? 답정너인거 같아 죄송합니당,,,

2023-10-02 16:14 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +  readModeReviewContent = '리뷰'
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/a3f77e04b05fcd12a81119f976d0dc278ed42b34#diff-4b8ae2495983bb2ac6378048f00a9113a977027de98963d259a27f5437cb9424)

2023-10-02 16:27 UTC, chojooyoung commented on src/hooks/useModals.ts
> +const useModals = (modalIds: string[]): UseModalReturnType => {
한 페이지내 모달을 여러개 관리하게 되는 상황까지 고려해서, 관련 state(isOpen,open,close)들이 많아 지는 것을 고려해 일단 짜보았는데요!!

[피그마링크](https://www.figma.com/file/PhqIqgC8ZJ1ovQTqLQuKKD/Price-Offer?node-id=3264%3A76594&mode=dev)
<img width="1021" alt="image" src="https://github.com/price-offer/offer-fe/assets/66211721/8eee7e1b-2397-4feb-8cb4-2097ada50fd1">

위처럼 판매/구매 탭 에서 관리해야 하는 모달이 두개이상인데, 각 어차피 각 모달의  state(isOpen,open,close) 를 정의해야 하니 이를 좀 더 편하게 관리해보고자 했었던 시도 였습니다. 😅

말씀주신데로 굳이...? 라는 느낌이 드네용

2023-10-02 16:28 UTC, chojooyoung commented on src/hooks/useModals.ts
> +const useModals = (modalIds: string[]): UseModalReturnType => {
오 레퍼런스 감사합니다! 좀 더 간단히 해서 재요청 드리겠습니다!

2023-10-02 16:41 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +    inputLength: 0,
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/70e9b2fc0526dc847b91765e7a144bc553cdde4b#diff-4b8ae2495983bb2ac6378048f00a9113a977027de98963d259a27f5437cb9424)

2023-10-02 16:43 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        </Styled.ReadModeReviewContentArea>
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/70e9b2fc0526dc847b91765e7a144bc553cdde4b#diff-4b8ae2495983bb2ac6378048f00a9113a977027de98963d259a27f5437cb9424)

2023-10-02 16:43 UTC, chojooyoung commented on src/components/mypage/ReviewModal/types.ts
> +  'isOpen' | 'onClose' | 'children'
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/70e9b2fc0526dc847b91765e7a144bc553cdde4b#diff-29c7f7afe8fb63dde87b575752c0dc3e45e6b0656eb17df24b06cda5fd0aed29)

2023-10-02 16:43 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +                    isGood={evaluate.state === 'smile'}
ods반영후 확인하겠습니다!

2023-10-02 16:45 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +  }
완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/a3f77e04b05fcd12a81119f976d0dc278ed42b34#diff-4b8ae2495983bb2ac6378048f00a9113a977027de98963d259a27f5437cb9424)

2023-10-02 16:46 UTC, chojooyoung commented on src/hooks/useModals.ts
> +  )
상태로 묶어서 관리하자는 말씀이신가요?.?

2023-10-02 16:54 UTC, chojooyoung commented on src/hooks/useModals.ts
> +const useModals = (modalIds: string[]): UseModalReturnType => {
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/16b159ff85d50f366609f8f100e17edfe847cdf8)
@shinhyojeong @sonsurim  확인부탁드립니다!

2023-10-02 16:56 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
반영완료!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/4a0b8de883135dabf64d041f7448b44bb5188984)

2023-10-03 08:36 UTC, sonsurim commented on src/components/common/AlertModal/index.tsx
> +      <Styled.ReviewConfirmButton onClick={(): void => onClickConfirmButton()}>
```suggestion
<Styled.ReviewConfirmButton onClick={onClickConfirmButton}>
```
그냥 적어주어도 될 것 같아요!

2023-10-03 08:39 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +  readModeReviewContent = '리뷰'
@chojooyoung 넴 요기 `타입으로 isReadMode가 true일 때만 해당 props를 받을 수 있는 형태`가 반영이 안되어있는 것 같아요!

2023-10-03 08:41 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +      {isReadMode ? (
@chojooyoung 전 이견 없습니다!! @shinhyojeong 확인 부탁드려융!

2023-10-03 08:45 UTC, sonsurim commented on src/components/mypage/ReviewModal/ReadReviewModal.stories.tsx
> +        }}>
```suggestion
        onClick={open}>
```
그냥 적어주어도 될 것 같습니다!

2023-10-03 08:45 UTC, sonsurim commented on src/components/mypage/ReviewModal/ReadReviewModal.stories.tsx
> +        }}
```suggestion
        onClose={close}
```
그냥 적어주어도 될 것 같습니다!

2023-10-03 08:45 UTC, sonsurim commented on src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
> +        }}>
```suggestion
        onClick={open}>
```

2023-10-03 08:46 UTC, sonsurim commented on src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
> +        }}
```suggestion
        onClose={close}
```

2023-10-03 08:46 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +        guideMessage={`${reviewState.reviewText?.length}/100`}
```suggestion
        guideMessage={`${reviewState.reviewText.length}/100`}
```
기본값이 string이어서 옵셔널 체이닝 안해주어도 될 것 같습니다!

2023-10-03 08:48 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +        onClick={(): void => onConfirm(reviewState)}>
```suggestion
const handleConfirm = () => {
  onConfirm(reviewState)
}

        onClick={handleConfirm}>
```
효정님 코멘트에도 남겨두었는데 함수 전,후 처리 없는 경우에는 인라인으로 적고 지금처럼 reviewState를 넣어서 호출해야하는 전 처리가 있는 경우 핸들러 함수로 분리하는 것이 추후 유지보수할 때 용이할 것 같은데 어떻게 생각하시나요??

2023-10-03 08:49 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +        onClick={(): void => onConfirm()}>
```suggestion
        onClick={onConfirm}>
```
여기도 바로 적어주어도 될 것 같습니다!

2023-10-03 08:52 UTC, sonsurim commented on src/pages/index.tsx
> +        isReadMode={false}
요거 타입에 정의된 부분이 없는데 혹시 어디에 명시된걸까요..!?

(+ 린트가 동작 안하는건가요..!?)

2023-10-03 08:54 UTC, sonsurim commented on src/pages/index.tsx
> +import { ReviewModal } from '@components/mypage/ReviewModal'
요기서 린트 에러 발생하는데 확인해주실 수 있을까요!?

2023-10-03 08:55 UTC, sonsurim commented on src/pages/index.tsx
> +        }}></ReviewModal>
여기 confirm은 어디에서 정의된건가요..?!

import쪽에서 에러가 발생해서 아래에서 린트 체킹이 안되는 것 같습니다!

2023-10-03 08:59 UTC, sonsurim commented on src/components/mypage/ReviewModal/index.tsx
> +const ReadReviewModal = ({
컴포넌트 외부 디렉토리로 분리하는 게 좋을 것 같습니다!

- mypage
  - ReviewModal
    - `ReadReviewModal`
      - index
      - types
    - `WriteReviewModal`
      - index
      - types

2023-10-03 13:42 UTC, chojooyoung commented on src/pages/index.tsx
> +        isReadMode={false}
아 컴포넌트 테스트 코드가 커밋에 들어간 것 같습니다.... ㅠㅠ 
린트는 동작하는데, 저 타입들이 정의되어있을떄 커밋을 한거라 린트에러가 안잡히고 들어 간 것 같아요!! 지우고 반영하겠숩니다!

2023-10-03 13:42 UTC, chojooyoung commented on src/pages/index.tsx
> +        }}></ReviewModal>
위 코멘트와 동일합니다 ㅠㅠ

2023-10-03 13:42 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        onClick={(): void => onConfirm(reviewState)}>
넵 너무 동의합니다 
효정님 코멘트도 확인하겠습니다!

2023-10-03 14:14 UTC, chojooyoung commented on src/components/common/AlertModal/index.tsx
> +      <Styled.ReviewConfirmButton onClick={(): void => onClickConfirmButton()}>
완완!~
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/ca11498b77db95c1dbeace45df75e90170aa134c#diff-08768223cb51d41ee8726f9e11b78640fecff8209b3c03c0986f90775f3fb7f8)

2023-10-03 14:15 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReadReviewModal.stories.tsx
> +        }}>
완완~!
[완완](https://github.com/price-offer/offer-fe/pull/108/commits/ca11498b77db95c1dbeace45df75e90170aa134c#diff-af7b7a7e2095ab5f6b418663a4dd500b9829627d71e3057a8c6ce606a48f9e1d)

2023-10-03 14:15 UTC, chojooyoung commented on src/components/mypage/ReviewModal/ReadReviewModal.stories.tsx
> +        }}
완완~!
[완완](https://github.com/price-offer/offer-fe/pull/108/commits/ca11498b77db95c1dbeace45df75e90170aa134c#diff-af7b7a7e2095ab5f6b418663a4dd500b9829627d71e3057a8c6ce606a48f9e1d)

2023-10-03 14:15 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
> +        }}>
완롼~!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/ca11498b77db95c1dbeace45df75e90170aa134c#diff-a50ee0006a725bfb8410677e8d28045060eb4c80f439f0c670babd7cdd61c23b)

2023-10-03 14:15 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
> +        }}
완롼~!
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/ca11498b77db95c1dbeace45df75e90170aa134c#diff-a50ee0006a725bfb8410677e8d28045060eb4c80f439f0c670babd7cdd61c23b)

2023-10-03 14:17 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        onClick={(): void => onConfirm(reviewState)}>
완롼~
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/fee8074b8f9f054f36734eeda9c8b6bd81a57cc9#diff-efe33139ad392b5168600bf34f17b3e692070a8d4f1bb8f20bc10c2f0ba7ab16)

2023-10-03 14:18 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        onClick={(): void => onConfirm()}>
완완~
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/fee8074b8f9f054f36734eeda9c8b6bd81a57cc9#diff-e09a102d293983acddee81c811bd4deba04f565e5018032ce85f3f73c603f943)

2023-10-03 14:21 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +const ReadReviewModal = ({
오 좋습니다~
- mypage
  - ReviewModal
    - `ReadReviewModal`
      - index
      - types
    - `WriteReviewModal`
      - index
      - types
    - `index`
    - `type`
    - `styled`
    - `stories`
    
   일단 요렇게 해보았는데, 보시고 코멘트 주시면 감사하겠숩니다

[완완](https://github.com/price-offer/offer-fe/pull/108/commits/fee8074b8f9f054f36734eeda9c8b6bd81a57cc9)

2023-10-03 14:22 UTC, chojooyoung commented on src/pages/index.tsx
> +        isReadMode={false}
[완롼](https://github.com/price-offer/offer-fe/pull/108/commits/f4989a5310ff37efbf3f1cf2d147eda705d140dd)

2023-10-03 14:51 UTC, sonsurim commented on src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
> +import type { WriteReviewModalProps } from './WriteReviewModal /types'
```suggestion
import type { WriteReviewModalProps } from './WriteReviewModal/types'
```
WriteReviewModal 디렉토리에 띄어쓰기가 포함되어 있어서 수정해서 올려야할 것 같습니다!

2023-10-03 15:34 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        guideMessage={`${reviewState.reviewText?.length}/100`}
[완료!](https://github.com/price-offer/offer-fe/pull/108/commits/d45593796d2ec7c49c4161da3621af7d44fb3859)

2023-10-03 15:35 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
> +import type { WriteReviewModalProps } from './WriteReviewModal /types'
[완료!](https://github.com/price-offer/offer-fe/pull/108/commits/d45593796d2ec7c49c4161da3621af7d44fb3859)

2023-10-03 15:39 UTC, chojooyoung commented on src/components/mypage/ReviewModal/index.tsx
> +        guideMessage={`${reviewState.reviewText?.length}/100`}
[완료!](https://github.com/price-offer/offer-fe/pull/108/commits/fee8074b8f9f054f36734eeda9c8b6bd81a57cc9#diff-efe33139ad392b5168600bf34f17b3e692070a8d4f1bb8f20bc10c2f0ba7ab16)

2023-10-04 11:49 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +  }
해당 훅에서 핸들러를 꺼내서 사용할 때 혼동이 올 여지가 있을 것 같아서 붙이는 것을 제안드렸어요 ~!~
요 부분에 대해서는 어떻게 생각하시나용 ? 🤔 @sonsurim @chojooyoung

2023-10-04 11:51 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +const useModals = (modalIds: string[]): UseModalReturnType => {
하나의 페이지에 여러개의 모달을 관리하는 부분은 생각 못했네요
요런 경우에는 주영님께서 짜신 것 처럼 여러개를 처리하도록 하는 방식이 더 깔끔할 것 같아요 👍👍!!

2023-10-04 12:05 UTC, shinhyojeong reviewed
현재 `ReviewModal/ReadReviewModal`과 `ReviewModal/WriteReviewModal`로 되어있는데
ReviewModal 하위에 있는 만큼 ReviewModal을 제거한 `Read`와 `Write`로 관리하는 것은 어떠신가요 ?
@chojooyoung @sonsurim

2023-10-04 12:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
reviewState.reviewScore이 null로 초기값을 가지고 있어서 해당 값으로 클릭 했는지 하지 않았는지에 대한 여부를 판단할 수 있을 것 같아용 !

2023-10-04 12:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +
요런 여백들은 의도하신 걸까요 ?

2023-10-04 12:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +                isFill={reviewState.reviewScore === scoreItem.state}
하위의 값과 중복돼 상수 처리하는게 가독성에 더 좋을 것 같습니다 ! 
```
const isSelectedValue = reviewState.reviewScore === scoreItem.state
```

2023-10-04 12:05 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/styled.ts
> +  ${({ theme }): string => theme.fonts.body01M};
@chojooyoung 요거 한번 더 확인부탁드령요 🤩!!

2023-10-04 12:08 UTC, sonsurim commented on src/hooks/useModals.ts
> +  }
@shinhyojeong 그 부분도 저는 동일합니다!

useModal의 반환값으로 modal의 close를 의미하고 있어 의미 자체는 혼동이 없을거라 생각이 듭니다. useModal을 여러개 사용하게 되어서 동일한 변수명이 문제가 된다면 사용할 때, 이름을 변경하는 것이 더 좋아보여요

```ts
const { close: closeModal } = useModal()
```

2023-10-04 12:10 UTC, sonsurim commented
@price-offer/offer-fe 지금 형태, 효정님이 말씀주신 형태 둘 다 좋습니당~

2023-10-04 12:15 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +  }
저는 다른 핸들러와 함께 사용될 때 
```
const { oepn } = useModal()

const handleClickButton = (e) => {
   console.log(e.target.value)
   open()
}
```

요런 상황이라면 handleClickButton을 파악하기 위해 어떤것을 open 하는지 변수명만으로 파악하기 어려울 것으로 생각돼요 !
이를 위해 핸들러에도 어떤 것을 다루는지에 대한 명확한 이름을 두면 코드가 더 쉬워질 것 같습니다 !

2023-10-04 12:21 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
오 좋슴다!!

2023-10-04 12:24 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +                isFill={reviewState.reviewScore === scoreItem.state}
MOCK_SCORE 를 map으로 돌고있어서 이를 상수화 하려면 MOCK_SCORE의 접근을 위한 함수가 생기는데,
상수화 보다는 그대로가 더 좋아보입니다!

2023-10-04 12:31 UTC, sonsurim commented on src/hooks/useModals.ts
> +  }
(사실 크리티컬하지 않은 부분이라 변경해도 될 것 같은데 예시로 들어주신 코드를 보고 효정님 의견이 궁금하여 여쭤봅니다..!)

> 핸들러에도 어떤 것을 다루는지에 대한 명확한 이름을 두면 코드가 더 쉬워질 것 같습니다 !

말씀주신 위의 `handleClickButton`의 예시는 open, openModal 네이밍 수정과의 관계성이 멀어 보이는 것 같아요. 예시로 들어주신 상황에서는 핸들러의 이름 변경이 필요하다고 생각이 됩니다.

- Case1
```ts
const { oepn } = useModal()

const handleOpenModal = (e) => {
   console.log(e.target.value)
   open()
}
```

Case1처럼 수정을 하고 보니, 핸들러 함수에서 해당 동작에 대해 정의를 하고 있어 이미 유추를 할 수 있는 상황인데 useModal return 함수에 또 컨텍스트를 포함해야 하는지도 함께 고민이 드는 것 같습니다.


- Case2
```ts
const { oepnModal } = useModal()

const handleOpenModal = (e) => {
   console.log(e.target.value)
   openModal()
}
```

정님 의견은 어떠신가요???

2023-10-04 12:36 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +  }
제가 생각한 케이스 설명이 부족했던 것 같아요 !
단순히 버튼을 클릭했을 때 모달만 연다면 Case1처럼 핸들러 네이밍을 변경하면 되지만
버튼 클릭시에 필요한 로직이 있고, 해당 로직 뒤에 모달을 열어야한다면 
`handleOpenModal`로 네이밍을 변경하는 것이 적절하지 않을 것으로 생각했어요 !

2023-10-04 12:40 UTC, sonsurim commented on src/hooks/useModals.ts
> +  }
```ts
const { open: openModal } = useModal()
```

아하 이해했습니다~ 그렇다면 혹시 위의 예시로 사용하는 측에서 변경하는 거에 대해서는 어떻게 생각하시는지 추가로 의견 여쭤봐도 될까요??

2023-10-04 12:50 UTC, shinhyojeong commented on src/hooks/useModals.ts
> +  }
단순히 open -> openModal로 변경해서 사용할 상황이 어떤것이 있을지 고민이 됩니다 !

제가 앞서 이야기한 핸들러의 이름을 명확히 지정하기 위한 재선언 이라면 
useModal을 사용하는 모든 경우에 핸들러의 이름을 재선언해주는 작업이 필요하게 돼 불필요한 작업이 늘어날 것 이라고 생각됩니다. 
또 협업시 openModal을 기본 핸들러 이름으로 사용하도록 강제할 수 없어
일관성을 위해서라도 useModal에서 기본 핸들러 이름을 명확하게 내보내주는 것이 좋다고 생각해요 !~

2023-10-04 12:53 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +  const [isClickReviewIcon, setIsClickReViewIcon] = useState<boolean>(false)
완완!@
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/b810798188ded9af6d7ee19245e766f6471d8464#diff-375895e9604bd3e30423eb04602702a93db13457791fc59281ba83be498a5038)

2023-10-04 12:53 UTC, sonsurim commented on src/hooks/useModals.ts
> +  }
좋습니다~~ 
@chojooyoung 님 의견 부탁드립니당

2023-10-04 12:53 UTC, chojooyoung commented on src/components/mypage/ReviewModal/WriteReviewModal/index.tsx
> +
[완료](https://github.com/price-offer/offer-fe/pull/108/commits/b810798188ded9af6d7ee19245e766f6471d8464#diff-0775211bfb94ce8db71d92cda0e9b92979ae62c2e39ab483e35f3628ee7ba412)

2023-10-04 12:55 UTC, chojooyoung commented on src/components/mypage/ReviewModal/styled.ts
> +  }
@shinhyojeong 효정님 상위에서 한번에 처리했습니다!

2023-10-04 13:00 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/styled.ts
> +  }
헙 주영님 제가 말씀드린 부분은 스타일을 상수로 빼는 방법이었어요 !

```
const applyStateStyle = (isFill:boolean) => css`
    color: ${isFill ? theme.colors.brandPrimary : theme.colors.grayScale30};
    ${theme.fonts.body01M};
`
```
요렇게 함수로 빼서 필요한 곳에만 적용해주는 것이 더 좋을 것 같아요 !!

2023-10-04 13:06 UTC, chojooyoung commented on src/hooks/useModals.ts
> +  }
호호 앞서 두분이 너무 좋은의견 주셔서 두분의 의견에 다 동의합니다!

함수의 이름은 그 기능을 명확하게 나타내는 것이 좋다고 생각해요!
따라서 효정님이 제시주신 openModal과 closeModal로 변경하는 것이 함수들이 모달을 열고 닫는 동작을 수행한다는 것을 더 명확하게 알 수 있을 것 같네용 👍 

그러나 이 함수들이 오직 모달 컨트롤만 위해 존재하고 다른 컨텍스트에서 해석될 여지가 없다면, open과 close라는 간결한 이름도 충분히 의미를 전달할 수 있기에 수림님 의견도 동의합니다!

일단 수림님이 효정님 의견에 동의하셨고, 더명확한 것이 좋다는 방향으로 결론이 나는 것 같아  openModal과 closeModal로 변경하겠숩니다! @shinhyojeong @sonsurim

2023-10-04 13:07 UTC, chojooyoung commented on src/components/mypage/ReviewModal/styled.ts
> +  }
스타일로 상수로 안뺴고, 중복을 없앤 이 방법은 어떻게 보시나요? ㅎㅎ

2023-10-04 13:12 UTC, chojooyoung commented on src/hooks/useModals.ts
> +  }
[링크](https://github.com/price-offer/offer-fe/pull/108/commits/1db8873aa8c3407d251b95ef7e43a0ee9a8914b2)
반영완료!

2023-10-04 13:16 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/styled.ts
> +  }
`*` 태그가 내부에 어떤 것이 있는지 명확하게 알지 못하는 상황에서 어떤 부분에 적용될지 
명확하게 알지 못하기 때문에 상수로 빼서 필요한 곳에 적용하는 것이
코드 이해에 더 좋을 것 같습니다 !

2023-10-04 13:21 UTC, chojooyoung commented on src/components/mypage/ReviewModal/styled.ts
> +  }
`* {} `태그는 하위 아래 모든 태그에 적용한다는 뜻입니다!
따라서 사용된 스타일 코드 아래 모든 태그들의 컬러가 해당 조건에 따라 분기처리된다고 명확하게 이해가 갈 수 있는 부분이라고 생각합니다! 
이렇게 하면 불필요한 상수화를 하지 않고도 중복을 없애는 방법이라 이렇게 해보았는데, 어떻게 생각하시나요?!

2023-10-04 13:23 UTC, shinhyojeong approved these changes, later dismissed
주영님 넘넘나리 수고 많으셨습니다 🤩🤩

2023-10-04 13:23 UTC, shinhyojeong commented on src/components/mypage/ReviewModal/styled.ts
> +  }
좋습니다 ! ㅎㅎ 하위 ReviewText 요 불필요한 태그만 제거해주시면 될 것 같아요 !

2023-10-04 14:04 UTC, sonsurim approved these changes
LGTM 👍👍
고생 많으셨습니당 ㅎㅎ

2023-10-04 14:04 UTC, merged