fix: 스토리북 폰트 깨지는 이슈 수정
price-offer/offer-fe pull request #114
Opened 2023-09-04 15:01 UTC by shinhyojeong

## 🔗 이슈 번호

- closed #113 

## ⛳ 구현 사항
* fix: 스토리북 폰트 깨지는 이슈 수정

2023-09-08 10:02 UTC, sonsurim commented on src/styles/global.tsx
> +    font-family: 'Pretendard', 'serif';
어떤 차이가 있는건가요?!

2023-09-09 08:35 UTC, shinhyojeong commented on src/styles/global.tsx
> +    font-family: 'Pretendard', 'serif';
Pretendard, serif 요렇게 작성하는 경우에는 Pretendard를 찾지 못하고 serif가 적용되더라구요 ㅠ_ㅠ! 근데 작은 따옴표로 폰트명을 감싸니 잘 적용돼서 요대로 수정했습니다 ☺️

2023-09-27 07:07 UTC, chojooyoung approved these changes, later dismissed
LGTM!

2023-09-28 08:29 UTC, sonsurim requested changes

2023-09-28 08:29 UTC, sonsurim commented on src/styles/global.tsx
> +    font-family: 'Pretendard', 'serif';
```suggestion
    font-family: 'Pretendard';
```
아하! 감사합니다!

serif 제공은 안해도 될 것 같은데 제거하는 거 어떠신가요??

2023-09-28 08:29 UTC, sonsurim commented on src/styles/global.tsx
> +    font-family: 'Pretendard', 'serif';
Pretendard cSpell workspace에 추가되면 좋을 것 같습니다!

2023-09-29 13:52 UTC, shinhyojeong commented on src/styles/global.tsx
> +    font-family: 'Pretendard', 'serif';
stylelint 룰에 default style이 설정되어야해서 추가해놓았는데 룰을 제거하는게 나을까용 ?

2023-09-29 13:57 UTC, shinhyojeong commented on src/styles/global.tsx
> +    font-family: 'Pretendard', 'serif';
[적용](https://github.com/price-offer/offer-fe/pull/114/commits/d7f3e363c1d608b3a3d7f1827140f15c38b52e78) 완료

2023-10-01 17:09 UTC, sonsurim approved these changes
LGTM 👍

2023-10-02 13:25 UTC, merged