feat: Confirm Modal 사용 방식 수정
price-offer/offer-fe pull request #118
Opened 2023-09-05 17:16 UTC by shinhyojeong

## 🔗 이슈 번호

- closed #100 

🌟 축 이슈 100 달성 🌟

## ⛳ 구현 사항
* ConfirmModal 리팩터링
* Storybook Next Image 이슈 수정

## 📚 구현 설명
* 'next/image'가 불러와진 곳의 스토리 북이 보이지 않는 이슈가 있어 수정했습니다~ [(참고자료)](https://engschool.tistory.com/91)
* ConfirmModal 이라기엔 로그인에도 사용되어질 모달이기 때문에 DefaultModal로 컴포넌트 명 변경했습니다.
* AlertModal이 따로 구현될 것 같아 아이콘을 보여주는 화면은 제거했습니다
### AlertModal
  <img width="246" alt="스크린샷 2023-09-06 오전 2 14 41" src="https://github.com/price-offer/offer-fe/assets/70738281/3c505d17-3b5f-46e8-82b3-e63826973c65">

## ⏳ 실행 화면 
<img width="518" alt="스크린샷 2023-09-06 오전 2 16 01" src="https://github.com/price-offer/offer-fe/assets/70738281/ac0c165d-8d0f-4bbf-a673-04b43739c3e9">

2023-09-08 10:04 UTC, sonsurim requested changes
충돌 확인 부탁드립니다!

효정넴 DefaultModal이랑 Offer의 Modal은 어떤 차이가 있는건가요??

> ConfirmModal 이라기엔 로그인에도 사용되어질 모달이기 때문에

요 부분에서 왜 변경이 되어야 하는지 여쭤보고 싶습니다!

2023-09-09 08:31 UTC, shinhyojeong commented
ds에 있는 모달은 빈 모달이구 현재 Default 모달은 offer-fe내에서 기본적으로 사용되는 모달의 형태를 띕니다 ! (PR 실행 이미지 속 형태)

2023-09-09 11:37 UTC, sonsurim commented
@shinhyojeong 답변 감사합니둥!
위와 같은 이유라면 기본이라고 하기에는 기본 이외의 역할도 하는 것 같아 DefaultModal보다 CommonModal이 더 어울릴 것 같은데 어떠신가요?? 
- Default : 기본
- Common : 공통

2023-09-09 14:55 UTC, shinhyojeong commented
@sonsurim 홍뇽뇽 넘 좋은 것 같습니다 ! Common 모달로 변경해놓을게요

2023-09-09 15:00 UTC, shinhyojeong commented
@sonsurim [변경 완료](https://github.com/price-offer/offer-fe/pull/118/commits/65770999b3618d1996765b6dc832a092ef1e48e3) 했습니다 !

2023-09-27 07:06 UTC, chojooyoung reviewed
CommonModal 이 더 명확해서 좋은 것 같습니다!

2023-09-27 07:06 UTC, chojooyoung commented on src/components/common/CommonModal/types.ts
> +}
title 은 ReactNode로 받고, description은 string 인 이유가 있을까요?.? 
하나로 통일 해도 괜찮을꺼 같숩니당! (확장성을 위해서라면 둘다 ReactNode로 받거나...등등 )

2023-09-28 08:34 UTC, sonsurim requested changes

2023-09-28 08:34 UTC, sonsurim commented on src/components/common/CommonModal/types.ts
> +}
둘 다 ReactNode로 받고 falsy값은 들어오지 못하게 하는 것도 좋은 것 같네요!

2023-09-29 13:22 UTC, shinhyojeong commented on src/components/common/CommonModal/types.ts
> +}
> 하나로 통일 해도 괜찮을꺼 같숩니당!

동의합니다 ! 

@sonsurim
저희 ui상 title, description이 동일한 스타일을 가지고 있기 때문에 string으로 통일하는 것이 좋을 것 같은데 
ReactNode로 통일하는 것을 제안하신 이유가 궁금합니다 !~

2023-10-01 17:12 UTC, sonsurim commented on src/components/common/CommonModal/types.ts
> +}
@shinhyojeong 주영넴 코멘트처럼 title만 ReactNode로 되어 있어서 확장성 고려가 필요한 부분인가 싶어서 Node로 제안드렸습니당!
string으로 통일되어도 괜찮으면 string 좋습니당 ㅎㅎ

2023-10-02 13:25 UTC, shinhyojeong commented on src/components/common/CommonModal/types.ts
> +}
[반영](https://github.com/price-offer/offer-fe/pull/118/commits/0fbc3e53096b85b755a703aec20d52e11ea70949) 완료 !

2023-10-03 09:01 UTC, sonsurim approved these changes
브랜치 업데이트하고 머지 부탁드려유!!

2023-10-03 14:26 UTC, merged