config: jotai 환경 세팅
price-offer/offer-fe pull request #135
Opened 2023-10-14 13:27 UTC by shinhyojeong

## 🔗 이슈 번호

- closed #131 

## ⛳ 구현 사항
* jotai 환경 세팅
   * jotai

2023-10-15 06:12 UTC, sonsurim approved these changes
LGTM 👍

2023-10-15 06:13 UTC, sonsurim requested changes
앗 효졍넴 jotai-query 세팅도 같이 해쥬셔야할 것 같습니당

https://jotai.org/docs/integrations/query

2023-10-16 12:29 UTC, shinhyojeong commented
@sonsurim 님 추가 설치 완려했습니다 🤩!!

2023-10-18 06:34 UTC, chojooyoung commented
lgtm~

2023-10-18 06:34 UTC, chojooyoung approved these changes

2023-10-18 12:36 UTC, sonsurim approved these changes
고생하셨습니당 ㅎㅎ
LGTM

2023-10-18 13:25 UTC, merged