fix:msw 디버깅
price-offer/offer-fe pull request #98
Opened 2023-08-04 07:57 UTC by chojooyoung

## 🔗 이슈 번호

- closed #97 

## ⛳ 구현 사항
문제원인:
msw가 셋팅되기전에 fetch함수를 부르는 것이 문제였다.
(개발자 도구 실행시에만 유효하다 => X)

해결방법:
상태를 하나 줘서 msw가 셋팅이 되었을경우에 app 랜딩

## 📚 구현 설명

2023-08-04 13:58 UTC, shinhyojeong submitted a review, later dismissed
우왕 넘 수고하셨슴다 ~

2023-08-04 13:58 UTC, shinhyojeong commented on src/pages/_app.tsx
> +  initMocks().then(() => setIsReadyMock(true))
a: 상위에 여백 있으면 좋을 것 같습니다 ! promise를 사용하신 이유가 있을까요 ?

2023-08-04 13:58 UTC, shinhyojeong commented on src/pages/_app.tsx
> +  if (!isReadyMock) return null
a: 가독성을 위해 if문에 중괄호를 생략하지 않는 것이 좋을 것 같은데 어떠신가요 ? 요건 같이 이야기해보고 [컨벤션](https://eslint.org/docs/latest/rules/curly)으로 정해도 좋을 것 같습니다 !

2023-08-04 14:10 UTC, sonsurim requested changes
주영넴 요거 next.js 공식 문서 예시처럼 하는건 어떠신가요!?

https://github.com/vercel/next.js/tree/canary/examples/with-msw

2023-08-04 14:12 UTC, sonsurim commented on src/pages/_app.tsx
> +  initMocks().then(() => setIsReadyMock(true))
이전에 설정한 initMocks가 promise로 설정되어서 인 것 같습니다 ㅎㅎ
내부적으로 dynamic import 하고 있어서 리턴 타입이 promise였어요!

2023-08-04 14:12 UTC, sonsurim commented on src/pages/_app.tsx
> +  if (!isReadyMock) return null
전 중괄호 넣는 것이 쥬아요~~ 주영넴 확인 되시믄 린트에 넣어주시죠

2023-08-06 11:25 UTC, chojooyoung commented
> 주영넴 요거 next.js 공식 문서 예시처럼 하는건 어떠신가요!?
> 
> https://github.com/vercel/next.js/tree/canary/examples/with-msw

공식문서 예시처럼이라는것이 어떤 의미인지 잘 모르겠서용 App위에서

2023-08-07 02:37 UTC, chojooyoung commented on src/pages/_app.tsx
> +  initMocks().then(() => setIsReadyMock(true))
여백은 린트에 잡히네유 ㅎㅎ

2023-08-12 05:40 UTC, shinhyojeong commented on src/pages/_app.tsx
> +  if (!isReadyMock) return null
주영넴 반영해주셔서 넣겠음둥

2023-08-22 08:19 UTC, sonsurim commented
@chojooyoung 
- https://github.com/vercel/next.js/blob/canary/examples/with-msw/mocks/index.ts#L1
- https://github.com/vercel/next.js/blob/canary/examples/with-msw/pages/_app.tsx#L4

앗 너무 늦게 확인했네요 ㅠㅠ 죄송함니다..! state 안쓰고 위의 형태로 하는 부분에 대한 이야기 였습니다!

2023-08-24 05:52 UTC, chojooyoung commented
> @chojooyoung
> 
> * https://github.com/vercel/next.js/blob/canary/examples/with-msw/mocks/index.ts#L1
> * https://github.com/vercel/next.js/blob/canary/examples/with-msw/pages/_app.tsx#L4
> 
> 앗 너무 늦게 확인했네요 ㅠㅠ 죄송함니다..! state 안쓰고 위의 형태로 하는 부분에 대한 이야기 였습니다!

동일한 형태로 변경해보아도 이슈가 뜨더라구요...!

2023-09-01 12:06 UTC, sonsurim commented
@chojooyoung 주영님!! 말씀주신대로 공식 예제를 Next13에서 했을 때는 동작하지 않네요.!
요거 top level await 으로 수정하는 것이 더 직관적일 것 같습니다.! top level await로 해당 모듈 import 된 이후 렌더링될 수 있도록 하는 방안이 좋을 것 같아요!!

https://github.com/seongbin9786/msw-with-nextjs-13/blob/main/pages/_app.tsx

2023-09-01 12:06 UTC, sonsurim commented
mypage쪽 지금 Tabs 관련해서 순환참조 이슈가 있어서 요 부분 해결하는 PR도 올려두겠습니다!

2023-09-01 12:08 UTC, sonsurim commented on .eslintrc.json
> +    "curly":"error",
안되어 있었다니.. 👍👍

2023-09-02 08:20 UTC, sonsurim approved these changes
LGTM!!!

2023-09-02 08:23 UTC, merged